import type { StoryboardPromptInput } from '../../shorts/prompts';
import {
  imageQuerySection,
  lengthSection,
  sceneFieldsSection,
  shapeOf,
  validValuesSection,
  voiceMechanicsSection,
} from '../../shorts/prompt-parts';
import { MAX_IMAGE_QUERIES, MIN_IMAGE_QUERIES } from '../../shorts/domain/storyboard';

/**
 * How "Não Có Vấn Đề" asks for a script.
 *
 * Same machinery as the fact channel, different problem. A fact short can fail
 * by being boring; this one fails by being *wrong in a way that sounds right*,
 * because popular psychology is the field with the widest gap between what
 * everyone repeats and what the research actually says. Ask a model for a
 * psychology short and it will reach, unprompted, for the ten percent of the
 * brain, for left-brain and right-brain personalities, for Mehrabian's 7-38-55,
 * for crossed arms meaning defensiveness. Every one of those is either a myth
 * or a real finding stretched past what it showed - and every one is more
 * quotable than the truth, which is why they spread.
 *
 * So the longest section of this prompt is a list of things it may not say.
 * That is the opposite balance from the fact channel, where the fight is
 * finding something worth forty-five seconds; here the material is endless and
 * the fight is not printing folklore.
 *
 * The second thing this channel owns is *shape*. A fact is told: here is a
 * strange thing, here is why it is true. A psychological trick is recognised:
 * here is a moment you have lived through, here is the mechanism behind it,
 * here is how you will notice it tomorrow. The viewer has to see themselves in
 * the first two seconds, or the rest is a lecture.
 */

export function buildStoryboardPrompt(input: StoryboardPromptInput): string {
  const shape = shapeOf(input.targetDurationSec);
  const { seconds, wordsPerScene } = shape;

  return [
    `Bạn đang viết kịch bản cho MỘT video ngắn tiếng Việt về **tâm lý và hành vi`,
    `con người** - kể trong khoảng ${seconds} giây, khung dọc 9:16, giọng nam miền Bắc`,
    `đọc trên nền ảnh chụp.`,
    ``,
    `Kênh tên là "Não Có Vấn Đề". Nó giải mã những chuyện kỳ lạ đang diễn ra`,
    `trong đầu và trong hành vi của con người: tâm lý, tình yêu, giao tiếp, thao`,
    `túng, ngôn ngữ cơ thể, và những "chiêu" tâm lý người ta gặp mỗi ngày mà`,
    `không gọi được tên. Đích đến của mỗi video là một câu người xem tự nói trong`,
    `đầu: "Ủa, sao não mình lại hoạt động như vậy?"`,
    ``,
    `Người xem đang lướt. Họ không tìm video này, nó tự hiện ra giữa hàng trăm`,
    `video khác, và họ quyết định ở lại hay vuốt qua trong khoảng hai giây. Rất`,
    `nhiều người xem trong trạng thái TẮT TIẾNG, chỉ đọc phụ đề. Viết với hai điều`,
    `đó trong đầu suốt từ đầu đến cuối.`,
    ``,
    `## Yêu cầu số một: tâm lý học thật, không phải tâm lý học vỉa hè`,
    ``,
    `Đây là phần khó nhất của kênh này, và là phần bạn phải cẩn thận nhất.`,
    ``,
    `Tâm lý học phổ thông đầy những câu nghe rất thuyết phục mà sai. Chúng lan`,
    `nhanh chính vì dễ nhớ và dễ kể lại - nghĩa là chúng cũng chính là những thứ`,
    `đầu tiên bật ra khi ai đó được yêu cầu viết về tâm lý. Đăng một cái là mất`,
    `toàn bộ người xem có học hành tử tế, và họ là những người bình luận.`,
    ``,
    `**Tuyệt đối không dùng những thứ sau, chúng đã bị bác bỏ hoặc bị kể quá lời:**`,
    ``,
    `- "Con người chỉ dùng 10% bộ não."`,
    `- "Người não trái thì lý trí, người não phải thì sáng tạo." Hai bán cầu có`,
    `  phân công thật, nhưng không hề chia người ra làm hai kiểu tính cách.`,
    `- "Mỗi người có một phong cách học tập riêng (nhìn / nghe / vận động), dạy`,
    `  đúng kiểu thì học tốt hơn." Đã kiểm chứng nhiều lần và không thấy hiệu quả.`,
    `- Quy tắc "7% lời nói - 38% giọng - 55% cơ thể" của Mehrabian. Con số có`,
    `  thật nhưng chỉ đúng trong đúng một tình huống hẹp: khi người nghe đang đoán`,
    `  *cảm xúc* từ một lời nói mơ hồ. Nó không nói rằng nội dung chỉ chiếm 7%.`,
    `- "Khoanh tay là phòng thủ", "nhìn sang trái là đang nói dối", và mọi kiểu`,
    `  đọc vị nói dối qua ngôn ngữ cơ thể. Không có dấu hiệu cơ thể đơn lẻ nào`,
    `  chỉ ra lời nói dối - đây là kết luận nhất quán của cả một mảng nghiên cứu.`,
    `- Thí nghiệm nhà tù Stanford và thí nghiệm Milgram kể theo kiểu "con người ai`,
    `  cũng thành ác quỷ". Cả hai đều đã bị xem xét lại nặng nề về cách tiến hành.`,
    `- "Hiệu ứng Mozart" làm trẻ thông minh hơn.`,
    `- "21 ngày là tạo được một thói quen." Con số này đến từ một cuốn sách phẫu`,
    `  thuật thẩm mỹ, không phải từ nghiên cứu về thói quen.`,
    `- Quảng cáo tiềm thức chèn hình vài phần nghìn giây điều khiển được người mua.`,
    `- Tháp nhu cầu Maslow hiểu như một cái thang phải leo hết bậc dưới mới lên`,
    `  bậc trên. Maslow không nói vậy, và phần thang bậc chưa từng được chứng minh.`,
    ``,
    `**Thay vào đó, hãy lấy từ những thứ đã được lặp lại nhiều lần và vẫn đứng`,
    `vững**: hiệu ứng mỏ neo, hiệu ứng hào quang, thiên kiến xác nhận, hiệu ứng`,
    `Zeigarnik, sự có đi có lại, tâm lý khan hiếm, hiệu ứng người ngoài cuộc,`,
    `chi phí chìm, hiệu ứng đóng khung, trí nhớ được dựng lại chứ không phải được`,
    `phát lại, thích nghi khoái lạc, hiệu ứng phơi nhiễm đơn thuần, sự bất hoà`,
    `nhận thức. Danh sách này là ví dụ, không phải giới hạn.`,
    ``,
    `Và những quy tắc chung này vẫn áp dụng:`,
    ``,
    `- Không bịa số liệu, năm, tên nghiên cứu, tên nhà nghiên cứu, tên đại học.`,
    `  Thà nói "nhiều nghiên cứu cho thấy" còn hơn bịa "một nghiên cứu năm 2017`,
    `  tại Đại học Harvard".`,
    `- Không biến một hiệu ứng có thật thành một quy luật tuyệt đối. Tâm lý học`,
    `  nói về xu hướng trung bình, không phải về từng con người. Nếu hiệu ứng chỉ`,
    `  đúng trong một số hoàn cảnh, nói luôn hoàn cảnh đó trong câu.`,
    `- Không chẩn đoán bệnh. Kênh này không nói ai bị trầm cảm, rối loạn nhân`,
    `  cách hay tự kỷ, và không đưa lời khuyên điều trị.`,
    ``,
    `## Yêu cầu số hai: người xem phải thấy chính mình trong hai giây đầu`,
    ``,
    `Đây là chỗ kênh này khác một kênh fact. Một sự thật lạ thì tự nó đã hấp dẫn.`,
    `Một hiệu ứng tâm lý thì không - cho đến khi người xem nhận ra họ vừa bị nó`,
    `tác động tuần trước.`,
    ``,
    `Vì vậy câu đầu tiên nên là MỘT TÌNH HUỐNG NGƯỜI XEM ĐÃ TỪNG SỐNG QUA, kể`,
    `bằng ngôn ngữ đời thường - rồi mới đến chuyện nó có tên gọi. Không chào hỏi,`,
    `không "hôm nay chúng ta sẽ tìm hiểu", không hỏi tu từ kiểu "bạn có bao giờ`,
    `tự hỏi không".`,
    ``,
    `Tốt:   "Cái áo hai triệu tự nhiên thành rẻ, chỉ vì bên cạnh nó treo cái năm triệu."`,
    `Tốt:   "Bài hát bạn ghét, nghe đến lần thứ mười thì tự nhiên thấy hay."`,
    `Tốt:   "Người ta cho bạn miếng dùng thử, và bạn thấy khó xử nếu không mua."`,
    `Tệ:    "Xin chào các bạn, hôm nay mình nói về hiệu ứng mỏ neo."`,
    `Tệ:    "Bạn có bao giờ tự hỏi tại sao mình lại mua sắm không?"`,
    `Tệ:    "Hiệu ứng mỏ neo là một thiên kiến nhận thức phổ biến."`,
    ``,
    `Nguyên tắc: **cảnh mở đầu tả hiện tượng, không gọi tên nó.** Tên gọi để dành`,
    `cho cảnh thứ hai, và lúc đó nó trở thành phần thưởng chứ không phải bài học.`,
    ``,
    `## Nếu video nói về thao túng`,
    ``,
    `Kênh có nói về thao túng, và cách nói là **để người xem nhận ra khi mình bị`,
    `làm vậy**, không phải để họ đi làm vậy với người khác. Cùng một nội dung,`,
    `khác cái đích:`,
    ``,
    `  Tốt: "Khi ai đó mở lời bằng một con số cao vô lý, họ đang neo bạn - biết`,
    `  vậy thì con số đó mất tác dụng."`,
    `  Tệ:  "Muốn ép giá, hãy đưa ra một con số cao vô lý trước."`,
    ``,
    `Viết ở phía người bị tác động, không ở phía người tác động.`,
    ``,
    ...lengthSection(shape),
    `## Nội dung video này`,
    ``,
    input.brief?.context
      ? [
          `ĐÂY LÀ CHỈ DẪN QUAN TRỌNG NHẤT VỀ NỘI DUNG. Video nói đúng về điều này,`,
          `không được đổi sang chủ đề khác dễ viết hơn:`,
          ``,
          `"${input.brief.context}"`,
          ``,
          `Nếu ảnh có sẵn không khớp hoàn hảo, chọn ảnh gần nhất và cứ viết về chủ`,
          `đề đó. Ảnh minh hoạ cho nội dung, chứ không quyết định nội dung.`,
        ].join('\n')
      : [
          `Người dùng chưa chọn chủ đề, nên bạn tự chọn một hiệu ứng tâm lý hoặc`,
          `một kiểu hành vi đáng kể: một thiên kiến trong lúc mua bán, một thứ xảy`,
          `ra giữa hai người đang yêu, một chỗ trí nhớ đánh lừa, một chiêu trong`,
          `giao tiếp hằng ngày, một điều xảy ra trong đám đông.`,
          ``,
          `Chọn thứ mà một người Việt bình thường ĐÃ TỪNG TRẢI QUA nhưng chưa gọi`,
          `được tên. Cảm giác "à hoá ra cái đó có tên" chính là thứ khiến người ta`,
          `xem hết và gửi cho bạn bè.`,
        ].join('\n'),
    ``,
    `## Câu mở đầu`,
    ``,
    input.brief?.hook
      ? [
          `Cảnh đầu tiên phải mang ý này. Viết lại bằng giọng của video chứ đừng`,
          `chép nguyên, nhưng giữ đúng nghĩa:`,
          ``,
          `"${input.brief.hook}"`,
        ].join('\n')
      : [
          `Tự viết câu mở theo đúng nguyên tắc "hai giây đầu tiên" ở trên: một`,
          `tình huống đời thường người xem đã từng sống qua, chưa gọi tên hiệu ứng.`,
        ].join('\n'),
    ``,
    `## Một lưu ý riêng của kênh này về ảnh`,
    ``,
    `Chủ đề ở đây gần như luôn TRỪU TƯỢNG - một thiên kiến, một cảm giác, một cơ`,
    `chế trong đầu. Không có kho ảnh nào chụp được "sự bất hoà nhận thức".`,
    ``,
    `Cách chữa là **chụp cái tình huống, đừng chụp cái khái niệm**. Mọi hiệu ứng`,
    `tâm lý đều xảy ra ở một chỗ có thật, giữa những người có thật:`,
    ``,
    `    bất hoà nhận thức   → "person thinking window" chứ không phải "cognitive dissonance"`,
    `    hiệu ứng mỏ neo     → "price tags shop", "shopping mall people"`,
    `    hiệu ứng người ngoài cuộc → "crowded street people", "subway crowd"`,
    `    ngôn ngữ cơ thể     → "two people talking", "job interview office"`,
    `    tình yêu, hẹn hò    → "couple holding hands", "couple cafe"`,
    `    trí nhớ             → "old photographs", "empty classroom"`,
    ``,
    `Ảnh người và ảnh sinh hoạt đời thường thì kho ảnh mở có rất nhiều, nên kênh`,
    `này thực ra dễ tìm ảnh hơn - miễn là bạn chịu dịch khái niệm thành khung`,
    `cảnh trước khi viết truy vấn.`,
    ``,
    ...imageQuerySection(),
    `## Tư liệu tham khảo`,
    ``,
    input.info
      ? [
          '```json',
          JSON.stringify(input.info, null, 2),
          '```',
          ``,
          `File này là danh sách trắng cho mọi thứ kiểm chứng được. Bạn được diễn`,
          `đạt lại nội dung trong đó. Bạn KHÔNG được nêu con số, tên nghiên cứu hay`,
          `chứng nhận nào không có trong file - có một bước kiểm tra máy móc sẽ`,
          `loại chúng, và nó không đọc được ý định của bạn.`,
        ].join('\n')
      : [
          `(Không có info.json - video này không quảng cáo sản phẩm nào.)`,
          ``,
          `Viết từ kiến thức chung, và chỉ viết phần bạn chắc chắn. Xem lại mục`,
          `"tâm lý học thật" ở trên: đó là ràng buộc thật sự ở đây, không phải một`,
          `lời nhắc lịch sự.`,
        ].join('\n'),
    ``,
    `## Giọng văn: một người đang giải thích, không phải một người đang giảng`,
    ``,
    `Người đọc là một người đàn ông miền Bắc, giọng rõ, điềm đạm, hơi tinh quái.`,
    `Anh ta kể chuyện về não của bạn, và anh ta cũng có cái não đó - nên giọng là`,
    `đồng loã, không phải bề trên.`,
    ``,
    `**Đây là điều quan trọng nhất về cách viết:** cả video phải nghe như MỘT`,
    `người đang giải thích một chuyện cho bạn nghe, liền một mạch từ đầu đến`,
    `cuối - không phải một chuỗi câu rời rạc đọc nối vào nhau.`,
    ``,
    `Giọng đọc máy nghỉ khá lâu sau mỗi dấu chấm. Viết mười câu ngắn thì được`,
    `mười khoảng lặng, và video nghe như đọc từng gạch đầu dòng. Cách chữa nằm`,
    `hoàn toàn ở chỗ bạn đặt dấu câu:`,
    ``,
    `- **Nối các ý bằng dấu phẩy và từ nối** thay vì cắt thành câu riêng: "nên",`,
    `  "vì", "mà", "rồi", "trong khi", "đến mức". Một câu dài có ba dấu phẩy nghe`,
    `  trôi chảy hơn hẳn ba câu ngắn.`,
    `- **Mỗi đoạn giải thích nên là một hai câu dài**, không phải năm câu ngắn.`,
    ``,
    `  Đừng viết:  "Đây là hiệu ứng mỏ neo. Não bạn cần một mốc. Con số đầu tiên`,
    `  thành mốc đó. Mọi con số sau bị so với nó."`,
    ``,
    `  Hãy viết:   "Não bạn không định giá được cái áo đó từ con số không, nên nó`,
    `  bám vào con số đầu tiên nó nhìn thấy, và từ đó trở đi mọi mức giá khác đều`,
    `  được đo bằng cái mốc ấy."`,
    ``,
    `- Câu ngắn vẫn dùng được, nhưng để dành cho chỗ thật sự cần nhấn - câu hook`,
    `  mở đầu, và câu chốt cuối. Ở giữa thì viết liền.`,
    `- Tiếng Việt nói, không phải tiếng Việt viết. Đọc thành tiếng thử: nếu nghe`,
    `  như sách giáo khoa tâm lý thì viết lại.`,
    `- Xưng hô trung tính: "bạn" cho người xem, và tránh "mình", "tớ", "chúng ta`,
    `  hãy cùng". Không "các bạn ơi", không "anh em".`,
    `- **Gọi tên hiệu ứng đúng một lần**, ở chỗ nó xuất hiện tự nhiên nhất, rồi`,
    `  quay lại nói bằng tiếng Việt đời thường. Rắc thuật ngữ khắp video là cách`,
    `  nhanh nhất biến nó thành bài giảng.`,
    `- Luôn trả lời "tại sao não làm vậy". Một video tâm lý hay không phải là`,
    `  danh sách hiệu ứng, mà là một mạch: hiện tượng → não đang giải quyết việc`,
    `  gì → vì thế nó đánh đổi cái gì.`,
    `- Cụ thể hơn là trừu tượng. Một ví dụ đời thường bằng mười câu định nghĩa:`,
    `  cái áo trong cửa hàng, tin nhắn chưa trả lời, hàng người xếp trước quán.`,
    `- Không hô hào, không "hãy like và đăng ký kênh nhé", không "sốc", "kinh`,
    `  hoàng", "bạn sẽ không tin nổi". Không hứa "đọc vị bất kỳ ai trong 3 giây".`,
    `- Không emoji, không hashtag, không markdown trong lời đọc.`,
    ``,
    ...voiceMechanicsSection(),
    ...sceneFieldsSection(shape),
    `## Bố cục video`,
    ``,
    `- Cảnh đầu, type "intro": tình huống đời thường. Tả hiện tượng, chưa gọi tên.`,
    `- Các cảnh giữa, type "segment": gọi tên nó, rồi giải thích NÃO ĐANG LÀM GÌ.`,
    `  Đi theo một mạch: hiện tượng → não đang cố giải quyết việc gì → cái giá`,
    `  phải trả là gì → nó còn xuất hiện ở đâu nữa trong đời sống.`,
    `- Cảnh cuối, type "outro": trả lại cho người xem một thứ dùng được - một`,
    `  chỗ để nhận ra nó lần sau, hoặc một câu khiến họ nhìn lại chuyện đã xảy ra`,
    `  với mình. Đây là kênh về việc hiểu ra, nên câu chốt nên là một chỗ hiểu ra.`,
    ...(input.channelName
      ? [
          ``,
          `  Rồi mời đăng ký kênh, bằng ĐÚNG tên kênh: **${input.channelName}**.`,
          ``,
          `  Viết câu mời đó cho tự nhiên và gắn vào chính hiệu ứng vừa kể, đừng`,
          `  đọc như đọc quảng cáo. Nhắc tên kênh ĐÚNG MỘT LẦN.`,
          ``,
          `  **Mỗi video phải là một câu khác nhau.** Đây là mấy kiểu để bạn thấy`,
          `  khoảng dao động, KHÔNG phải mẫu để chép:`,
          ``,
          `    "Não còn nhiều trò như vậy lắm, ${input.channelName} kể dần."`,
          `    "Theo ${input.channelName} đi, để lần sau bạn bắt được nó sớm hơn."`,
          `    "Còn cả tá chuyện não làm sau lưng bạn, có ở ${input.channelName}."`,
          ``,
          `  Hay nhất là móc thẳng vào hiệu ứng vừa kể - nhắc lại chỗ bất ngờ nhất`,
          `  rồi mời xem tiếp. Một câu thôi, ngắn, đặt cuối cùng. Không "nhớ like`,
          `  và share", không "bấm chuông thông báo", không liệt kê ba thứ.`,
        ]
      : [`  Không xin like, không xin đăng ký.`]),
    ``,
    ...validValuesSection(input.defaultStyle, input.defaultVoice),
    `## Phần đăng YouTube`,
    ``,
    `Video được đăng dưới dạng YouTube Short, nên viết luôn phần đăng - một object`,
    `"publish" gồm "title", "description" và "tags". Tất cả bằng tiếng Việt.`,
    ``,
    `- **title**: tối đa 100 ký tự, nhưng người xem chỉ thấy khoảng 60 ký tự đầu`,
    `  trên khung Short. Nói thẳng vào hiện tượng, đúng giọng của video: "Vì sao`,
    `  cái áo đắt tự nhiên thành rẻ" là được; "BÍ MẬT TÂM LÝ 99% KHÔNG BIẾT" thì`,
    `  không. Không viết hoa toàn bộ, không emoji, không hứa đọc vị người khác.`,
    `- **description**: hai đến ba câu. Câu đầu nhắc lại hiện tượng, câu sau thêm`,
    `  một chỗ khác trong đời sống mà nó cũng xảy ra thì càng tốt. KHÔNG viết danh`,
    `  sách chương và KHÔNG viết dòng ghi nguồn nhạc - hệ thống tự sinh cả hai,`,
    `  kèm thẻ #shorts.`,
    `- **tags**: năm đến mười hai thẻ, chữ thường, là những từ người ta thực sự`,
    `  gõ tìm. Trộn thẻ rộng ("tâm lý học", "tâm lý", "hành vi con người") với`,
    `  thẻ riêng của video này ("hiệu ứng mỏ neo", "mua sắm").`,
    ``,
    `## Định dạng trả về`,
    ``,
    `Trả về DUY NHẤT một object JSON, không gì khác - không giải thích, không rào`,
    `markdown, không thêm chữ nào trước hay sau.`,
    ``,
    '```json',
    JSON.stringify(
      {
        version: '1.0',
        project: { id: input.projectId, episodeTitle: 'Tên của video này' },
        video: { style: input.defaultStyle },
        voice: { voice: input.defaultVoice },
        content: {
          summary: 'Một hai câu nói video này giải thích hiện tượng gì, để ghi chú nội bộ.',
          narration: '',
          imageQueries: ['price tags shop', 'shopping mall people', 'person thinking window'],
        },
        publish: {
          title: 'Vì sao cái áo đắt tự nhiên thành rẻ',
          description:
            'Cái áo hai triệu thành rẻ chỉ vì bên cạnh treo cái năm triệu - ' +
            'não bạn không định giá từ con số không, nó bám vào con số đầu tiên nhìn thấy.\n\n' +
            'Cũng chính là lý do món đắt nhất trong thực đơn hiếm khi để bán.',
          tags: ['tâm lý học', 'tâm lý', 'hiệu ứng mỏ neo', 'hành vi con người', 'mua sắm'],
        },
        scenes: [
          {
            id: 'scene-01',
            type: 'intro',
            imageQuery: 'price tags shop',
            title: 'Cái áo hai triệu',
            narration:
              'Cái áo hai triệu tự nhiên thành rẻ, chỉ vì người ta treo ngay bên ' +
              'cạnh nó một cái năm triệu,',
            duration: 5,
            animation: 'zoom-in',
            transition: 'fade',
            effect: 'none',
            overlay: 'dust',
          },
          {
            id: 'scene-02',
            type: 'segment',
            imageQuery: 'shopping mall people',
            title: '',
            narration:
              'và cái đó có tên là hiệu ứng mỏ neo: não bạn không định giá được ' +
              'từ con số không, nên nó bám vào con số đầu tiên nó nhìn thấy, rồi ' +
              'đo mọi thứ còn lại bằng cái mốc ấy.',
            duration: 5,
            animation: 'pan-right',
            transition: 'cut',
            effect: 'none',
            overlay: 'none',
          },
        ],
      },
      null,
      2,
    ),
    '```',
    ``,
    `Chú ý hai cảnh mẫu ở trên: câu của cảnh đầu chưa kết thúc, nó chạy tiếp sang`,
    `cảnh sau. Đó chính là kiểu viết cần có. Và chú ý cảnh một tả hiện tượng, cảnh`,
    `hai mới gọi tên - đó cũng chính là thứ tự cần có.`,
    ``,
    `Để "content.narration" là chuỗi rỗng - hệ thống tự nối lời đọc của các cảnh`,
    `lại. Mỗi "imageQuery" của cảnh phải trùng đúng một chuỗi trong`,
    `"content.imageQueries", và khai ${MIN_IMAGE_QUERIES}-${MAX_IMAGE_QUERIES} truy vấn. Tên tạm hiện tại là`,
    `"${input.workingTitle}"; hãy thay bằng tên thật của video.`,
  ].join('\n');
}
